---
title: "web_scrap_Sushmit_Dhar"
author: "Sushmit Dhar"
date: "`r format(Sys.time(), '%d %b %Y')`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(kableExtra)
library(rvest)     
library(tidyverse) 
library(knitr)     


# Insert start date and end date
from_date = as.Date('01.01.2019',format = "%d.%m.%Y" )
to_date = as.Date('01.09.2020',format = "%d.%m.%Y" )

url_base_1 <- "https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.0%d.2019&datoTil=01.0%d.2019&id_region=0&id_niva1=51&id_niva2=-+-+-&id_bransje1=0"

map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_1,i,i+1))
  
  data.frame(Type = html_text(html_nodes(page,'td td a'))
  )
             
}) -> mapped_type_1

map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_1,i,i+1))
  
  data.frame(Place = html_text(html_nodes(page,'td td:nth-child(2) p'))
  )
}) -> mapped_place_1

mapped_place_1<- mapped_place_1 %>% 
  filter(!grepl('Oslo', Place))%>% filter(!grepl('Rogaland', Place))%>%
  filter(!grepl('Møre og Romsdal', Place))%>% filter(!grepl('Nordland', Place))%>%
  filter(!grepl('Viken', Place))%>% filter(!grepl('Innlandet', Place))%>%
  filter(!grepl('Vestfold og Telemark', Place))%>%filter(!grepl('Agder', Place))%>% 
  filter(!grepl('Vestland', Place)) %>% filter(!grepl('Trøndelag', Place))%>% 
  filter(!grepl('Troms og Finnmark', Place))%>% filter(!grepl('Utenlands', Place)) %>%
  filter(!grepl('Svalbard', Place))


map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_1,i,i+1))
  
  data.frame(Date= html_text(html_nodes(page,'td:nth-child(6) p'))
  )
}) -> mapped_date_1
  
mapped_date_1 <- mapped_date_1 %>%   filter(!grepl('Dato', Date))  
mapped_date_1 <- data.frame(as.Date(mapped_date_1$Date, "%d.%m.%Y"))
colnames(mapped_date_1) <- c("Date")


Map_One <- tibble(mutate(mapped_place_1,mapped_date_1,mapped_type_1))

p_1 <- subset.data.frame(Map_One, Type=="Konkursåpning                                     \n                ")

###############################################################################################

url_base_2 <- "https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.%d.2019&datoTil=01.%d.2019&id_region=0&id_niva1=51&id_niva2=-+-+-&id_bransje1=0"

map_df(10:11, function(i) {
  page <- read_html(sprintf(url_base_2,i,i+1))
  
  data.frame(Type = html_text(html_nodes(page,'td td a'))
  )
  
}) -> mapped_type_2

map_df(10:11, function(i) {
  page <- read_html(sprintf(url_base_2,i,i+1))
  
  data.frame(Place = html_text(html_nodes(page,'td td:nth-child(2) p'))
  )
}) -> mapped_place_2

mapped_place_2 <- mapped_place_2 %>% 
  filter(!grepl('Oslo', Place))%>% filter(!grepl('Rogaland', Place))%>%
  filter(!grepl('Møre og Romsdal', Place))%>% filter(!grepl('Nordland', Place))%>%
  filter(!grepl('Viken', Place))%>% filter(!grepl('Innlandet', Place))%>%
  filter(!grepl('Vestfold og Telemark', Place))%>%filter(!grepl('Agder', Place))%>% 
  filter(!grepl('Vestland', Place)) %>% filter(!grepl('Trøndelag', Place))%>% 
  filter(!grepl('Troms og Finnmark', Place))%>% filter(!grepl('Utenlands', Place)) %>%
  filter(!grepl('Svalbard', Place))


map_df(10:11, function(i) {
  page <- read_html(sprintf(url_base_2,i,i+1))
  
  data.frame(Date= html_text(html_nodes(page,'td:nth-child(6) p'))
  )
}) -> mapped_date_2

mapped_date_2 <- mapped_date_2 %>%   filter(!grepl('Dato', Date))  
mapped_date_2 <- data.frame(as.Date(mapped_date_2$Date, "%d.%m.%Y"))
colnames(mapped_date_2) <- c("Date")


Map_Two <- tibble(mutate(mapped_place_2,mapped_date_2,mapped_type_2))

p_2 <- subset.data.frame(Map_Two, Type=="Konkursåpning                                     \n                ")
###############################################################################################


url_base_3 <- "https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.0%d.2020&datoTil=01.0%d.2020&id_region=0&id_niva1=51&id_niva2=-+-+-&id_bransje1=0"

map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_3,i,i+1))
  
  data.frame(Type = html_text(html_nodes(page,'td td a'))
  )
  
}) -> mapped_type_3

map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_3,i,i+1))
  
  data.frame(Place = html_text(html_nodes(page,'td td:nth-child(2) p'))
  )
}) -> mapped_place_3

mapped_place_3 <- mapped_place_3 %>% 
  filter(!grepl('Oslo', Place))%>% filter(!grepl('Rogaland', Place))%>%
  filter(!grepl('Møre og Romsdal', Place))%>% filter(!grepl('Nordland', Place))%>%
  filter(!grepl('Viken', Place))%>% filter(!grepl('Innlandet', Place))%>%
  filter(!grepl('Vestfold og Telemark', Place))%>%filter(!grepl('Agder', Place))%>% 
  filter(!grepl('Vestland', Place)) %>% filter(!grepl('Trøndelag', Place))%>% 
  filter(!grepl('Troms og Finnmark', Place))%>% filter(!grepl('Utenlands', Place)) %>%
  filter(!grepl('Svalbard', Place))


map_df(1:8, function(i) {
  page <- read_html(sprintf(url_base_3,i,i+1))
  
  data.frame(Date= html_text(html_nodes(page,'td:nth-child(6) p'))
  )
}) -> mapped_date_3

mapped_date_3 <- mapped_date_3 %>%   filter(!grepl('Dato', Date))  
mapped_date_3 <- data.frame(as.Date(mapped_date_3$Date, "%d.%m.%Y"))
colnames(mapped_date_3) <- c("Date")


Map_Three <- tibble(mutate(mapped_place_3,mapped_date_3,mapped_type_3))

DF_2020 <- subset.data.frame(Map_Three, Type=="Konkursåpning                                     \n                ")

###############################################################################################

DF_2019 <- rbind.data.frame(p_1,p_2)

G_1 <- DF_2020 %>% group_by(Date) %>% summarize(count = n())
G_2 <- DF_2019 %>% group_by(Date) %>% summarize(count = n())

```


```{r plotBED}
ggplot() + 
  geom_line(data=G_1, aes(x=Date, y=count), color='green') + 
  geom_line(data=G_2, aes(x=Date, y=count), color='red')
```

